[build]
buildCommand = "npm install && npm run build"
watchPatterns = ["packages/web/**"]

[deploy]
startCommand = "npm run start -w packages/web"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
